# Generated by Django 4.2.4 on 2023-08-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
